### ISSUE TITLE
Example for make_error_middleware shows make_eval_exception

### ISSUE THREAD

**Issue by pmidford** [Pylons/weberror#12]
The readme.md and the writeup on pypi describe make_error_middleware and make_eval_exception, but the examples given are identical and show the use of make_eval_exception, with no mention of make_error_middleware.  I posted this on the pylons G+ forum, but it was never released, so I assume this is where this needs to go.

**Comment by mmerickel** [comment]
This library is not maintained. If you would like to see this fixed you will at the very least need to submit a working PR so that we can simply merge it.

**Comment by bertjwregeer** [comment]
I've fixed the README... still not a very useful example, feel free to submit a better doc.
