### ISSUE TITLE
Weberror is no more compatible with the pyramid debug toolbar

### ISSUE THREAD

**Issue by sbrunner** [Pylons/weberror#13]
see: https://github.com/Pylons/weberror/commit/911be5018a0980ca814fdfb3f38dbfdce640c3a5#commitcomment-16619254

**Comment by bertjwregeer** [comment]
Set a different debug url prefix when instantiating weberror, for example `_weberror_debug`.

I'll accept patches to fix the issue.

**Comment by sbrunner** [comment]
> Set a different debug url prefix when instantiating weberror, for example `_weberror_debug`.

I use it with paster and I don't find any way to set the config doesn't global_conf missing here:
https://github.com/Pylons/weberror/blob/911be5018a0980ca814fdfb3f38dbfdce640c3a5/weberror/evalexception.py#L801?
Or did I miss something?

> I'll accept patches to fix the issue.

Thanks, I will do it :-)

**Comment by bertjwregeer** [comment]
Merged this into master. Will cut a release.
