### ISSUE TITLE
Production deployment fails because of docstring manipulation.

### ISSUE THREAD

**Issue by amcgregor** [Pylons/weberror#19]
In an environment with `PYTHONOPTIMIZE=2` set in the environment, or where Python is otherwise invoked with the `-OO` (optimize & strip docstrings) option as distinct from `-O` (just optimize) WebError explodes gloriously upon reaching the end of `errormiddleware.py`:

```python
doc_lines = (ErrorMiddleware.__doc__ or '').splitlines(True)
for i in range(len(doc_lines)):
    if doc_lines[i].strip().startswith('Settings'):
        make_error_middleware.__doc__ = ''.join(doc_lines[i:])
        break
del i, doc_lines
```

The reason is due to `i` never having been initialized if the string is empty, which it is with this level of optimization enabled.  Instead, I would recommend:

```python
if ErrorMiddleware.__doc__:
    doc_lines = ErrorMiddleware.__doc__.splitlines(True)
    for i in range(len(doc_lines)):
        if doc_lines[i].strip().startswith('Settings'):
            make_error_middleware.__doc__ = ''.join(doc_lines[i:])
            break
    del i, doc_lines
```

A quick glance indicates this is a current problem (`master` branch) and has been a problem since at least `0.10.3`.

**Comment by bertjwregeer** [comment]
This software is no longer actively maintained. If you would like to maintain it, please let me know.

Otherwise, I will accept PR's and merge them into master, as well as release a new version.

**Comment by amcgregor** [comment]
Is there a preferred replacement or alternative middleware layer for interactive traceback diagnostics?

The fix is literally provided above; apologies for it not being a proper PR, the one additional line and block indent didn't seem to warrant forking, branching, committing, issuing, then hosting around that extra fork until accepted.  ;)  It's a minor problem, easily avoided by limiting production to single `-O` for now.  Most developers don't even seem to know `-O` exists.  :D

**Comment by bertjwregeer** [comment]
I am not aware of a direct replacement.

If you'd like to see a release with the fix, you will have to go through the fork/branch/commit cycle.

**Comment by amcgregor** [comment]
No worries then.  In scrounging, looks like [backlash](https://pypi.python.org/pypi/backlash) meets my needs, despite the comically small version number.  (Standalone extract of the Werkzeug debugger adapted to WebOb, last push 16 days ago.)
