### ISSUE TITLE
PyPI page points to the old repo

### ISSUE THREAD

**Issue by cclauss** [Pylons/weberror#20]
The **Home Page:** field https://pypi.python.org/pypi/WebError points to bitbucket instead of pointing here.

**Comment by bertjwregeer** [comment]
¯\_(ツ)_/¯

**Comment by stevepiercy** [comment]
This is set by the value of `url` in `setup.py`. It should also update it with links similar to [Pyramid's](https://github.com/Pylons/pyramid/blob/master/setup.py#L87-L92) and [render on PyPI](https://pypi.org/project/pyramid/).

**Comment by bertjwregeer** [comment]
No, this will not be actively maintained. In fact, if you had looked at the README for this, it states as much.

**Comment by cclauss** [comment]
Perhaps the repo should be [archived](https://help.github.com/en/articles/archiving-repositories) if it is no longer maintained.

**Comment by bertjwregeer** [comment]
@cclauss if you read the README... the only "maintenance" done is I will accept patches and push new versions to PyPi. Archiving this repo would not allow for that to happen. If you are @stevepiercy want to update the `setup.py` to point to the new location, I'll happily go push it up to pypi.
